// Command gendocs regenerates the Markdown command reference under
// docs/commands from pier's cobra command tree. Run it via `make docs`.
package main

import (
	"log"
	"os"

	"github.com/eseceve/pier/cmd"
	"github.com/spf13/cobra/doc"
)

const outDir = "docs/commands"

func main() {
	root := cmd.Root()
	// Suppress the "Auto generated by spf13/cobra on <date>" footer so the
	// generated files don't churn on every run.
	root.DisableAutoGenTag = true

	if err := os.MkdirAll(outDir, 0o750); err != nil {
		log.Fatalf("gendocs: %v", err)
	}
	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		log.Fatalf("gendocs: %v", err)
	}
}
